### PR TITLE
Fix spelling of 'high score'

### PR DESCRIPTION
**Pull request by jaredsohn**

### CODE REVIEW

**Comment by AmitMY** [comment]
On the iphone, when the birdie dies, it does not get to the "Gameover" function, it just freezes

**Comment by jaredsohn** [comment]
Likely the text is too long.  One could fix it by reducing the font size, but I don't have time to invest in this.

**Comment by AmitMY** [comment]
I was running the code with no changes. I got to the website from my iphone, not costum code. On safari its not working
On chrome it is.

**Comment by jaredsohn** [comment]
You should open up a new issue then.  (The comments here should be about the pull request I made to change HISCORE to HIGHSCORE.)

**Pull request closed without merging**
